apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop-dev
  labels:
    pro: roboshop
    component: mongodb
    tier: db

spec:
  replicas: 1
  selector:
    matchLabels:
      pro: roboshop
      component: mongodb
      tier: db

  template:
    metadata:
      labels:
        pro: roboshop
        component: mongodb
        tier: db

    spec:
      containers:
        - name: mongodb
          image: "{{ .Values.deployment.imagerepo }}:{{ .Values.deployment.version }}"
          ports:
            - containerPort: 27017

          readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 10
          periodSeconds: 10
          livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 5
          periodSeconds: 5